import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";

export default defineConfig({
    plugins: [
        laravel({
            input: [
                //css
                "resources/scss/icons.scss",
                "resources/scss/style.scss",
                "node_modules/gridjs/dist/theme/mermaid.css",
                "node_modules/gridjs/dist/theme/mermaid.min.css",
                "node_modules/select2/dist/css/select2.min.css",

                //js
                "resources/js/app.js",
                "resources/js/config.js",
                "resources/js/murid/dashboard-murid.js",
                "resources/js/admin/tabel.js",
                "resources/js/admin/tabel-jadwal.js",
                "resources/js/admin/select2-init.js",
                "resources/js/admin/dashboard.js",
                "resources/js/admin/manage-user.js",
                "resources/css/admin/manage-user.css",
                "resources/js/admin/jadwal-pelajaran.js",
                "resources/css/admin/jadwal-pelajaran.css",
                "resources/js/admin/laporan.js",
                "resources/css/admin/laporan.css",
                "resources/js/admin/pengumuman.js",
                "resources/css/admin/pengumuman.css",
                "resources/js/admin/delegasi.js",
                "resources/css/admin/delegasi.css",
                "resources/js/admin/pengaturan.js",
                "resources/css/admin/pengaturan.css",
                "resources/js/admin/bantuan.js",
                "resources/css/admin/bantuan.css",
                "resources/js/guru/dashboard.js",
                "resources/css/guru/dashboard.css",
                "resources/js/guru/scan-qr.js",
                "resources/css/guru/scan-qr.css",
                "resources/js/guru/jadwal-mengajar.js",
                "resources/js/guru/status-absensi.js",
                "resources/css/guru/status-absensi.css",
                "resources/css/guru/delegasi.css",
                "resources/js/guru/permohonan-izin.js",
                "resources/css/guru/pengumuman-guru.css",
                "resources/js/guru/pengumuman-guru.js",
                "resources/js/guru/pengaturan-guru.js",
                "resources/css/murid/dashboard.css",
                "resources/css/murid/qr-absensi.css",
                "resources/js/murid/qr-absensi.js",
                "resources/js/murid/jadwal-pelajaran.js",
                "resources/js/murid/riwayat-absensi.js",
                "resources/js/murid/delegasi.js",
                "resources/css/murid/pengumuman.css",
                "resources/js/murid/pengumuman.js",
                "resources/js/murid/permohonan-izin.js",
                "resources/js/murid/pengaturan.js",
                "resources/js/murid/bantuan.js",
                "resources/css/components/pengaturan.css",
            ],
            refresh: true,
        }),
    ],
});
